### ISSUE TITLE
Sprite's child(Sprite) can not set to invisible?

### ISSUE THREAD

**Issue by minihope** [cocos2d/CocosBuilder#126]
i set child to invisible and save the file. but when i publish the project, the child are still visible.

**Comment by Tw0bit** [comment]
@minihope I too have had this issue - the work around I use is to set the scale to 0 and then do an instant animation to scale 1.

If you set a Visible keyframe later in the sequence the Sprite will be hidden until then, unfortunately it still requires a visible frame in the future.

Note: this is from my personal experience with CocosBuilder since v3 alpha1 (became 2.1beta).

**Comment by chuckzhang** [comment]
encountered this issue too...

**Comment by vlidholt** [comment]
Fixed
