### ISSUE TITLE
Crash when changing the "total particles" property

### ISSUE THREAD

**Issue by MartinCote** [cocos2d/CocosBuilder#192]
I had this issue with the latest master branch (commit b77e507) and from the 3.0 alpha build.

Repro steps:
1. Add a particle system.
2. Change the "total particles" property from 250 to 150.
3. Crash.

It seems to crash in cocos2d though, in [CCParticleSystemQuad postStep].

**Comment by MartinCote** [comment]
As an additional note, the `[CCParticleSystemQuad postStep]` method has a couple of options commented out.  When using option 2 it doesn't crash anymore.

**Comment by vlidholt** [comment]
This has now been fixed in cocos2d

**Comment by ttakamoto** [comment]
Its not fixed yet, right?

**Comment by MartinCote** [comment]
Yes it works now.

**Comment by ttakamoto** [comment]
I'm currently working with cocos2d 2.0.0 CCParticleSystem of CCParticleFlower and when I change the TotalParticles there's no crash but the effect doesn't show up in the layer either.

Is that fixed in the latest release?

**Comment by robgraeber** [comment]
I had the same problem ttakamoto had in 2.1, whenever changing the CCParticleSystemQuad's totalParticles over 250 (default), resulted in it not working/not showing up. This might be a Cocos2d problem because when I modified totalParticles via code, it had the same problem. 

Not sure if it persists in 3.0, I briefly tried loaded my ccb in 3.0 and while it didn't have the exactly the same problem, I increased totalParticles to 500 but in CocosBuilder it was acting like totalParticles was set to 250 (default).
