### ISSUE TITLE
How to update source code

### ISSUE THREAD

**Issue by bagusflyer** [cocos2d/CocosBuilder#248]
Sorry. I'm new to github. I've download and compile the source code for cocosbuilder without problem. My question is how to update my cocosbuilder to latest source code? Thanks

**Comment by petroslafaz** [comment]
If you have cloned the repository as described in the read me file (ie you've used the 'git clone https://github.com/cocos2d/CocosBuilder') then you're only one command away to get the new updates; You need to use 'git pull' to get the updates. Sometimes though the updates are only on the develop branch. In order to switch to this branch use 'git checkout develop'.

**Comment by vlidholt** [comment]
Also, whenever pulling new code you will need to:

```
git submodule update --init --recursive
```
