### ISSUE TITLE
CocosBuilder crash when choosing jpg file for sprite

### ISSUE THREAD

**Issue by pierrepaullavoie** [cocos2d/CocosBuilder#249]
1. Using the toolbar, create a CCSprite.
2. In the CCSprite properties, select a jpg image file for the Sprite frame.
3. CocosBuilder exit/crash

This is not a big issue but if jpg is not supported CocosBuilder could only list png files.

**Comment by vlidholt** [comment]
There is an issue with using jpg images when in the resources-auto folder.

**Comment by pierrepaullavoie** [comment]
This would explain the crash I was experiencing.

**Comment by vlidholt** [comment]
Automatic scaling should support jpg images. Short term, scaling and re-saving the jpg:s with a default compression is an acceptable solution. Longer term compression should be configurable per file, this could be implemented together with the planned file previews.

The copyFileIfChanged:... method in CCBPublisher is where the jpg images are being copied and createCachedImageFromAuto in ResourceManager is where the files are being rescaled.

A good way to solve this bug is by first creating a simple test case to reproduce it. (Create a project, add a resources-auto folder in the Resources with a jpg image in it, the Publish and Run it in CocosPlayer.)

**Comment by vlidholt** [comment]
Good work!

**Comment by vlidholt** [comment]
Noticed an issue with this fix. jpg-images do not crash CocosBuilder, but they are still saved as png-files. They should be saved as jpg-files.

**Comment by vlidholt** [comment]
To clarify, the images are saved as png images, but are using a jpg extension. Preview.app and the iOS loader will open them correctly, but png-images are larger (generally) than jpg-images.
