### ISSUE TITLE
Ability to disable anti-aliasing on nodes.

### ISSUE THREAD

**Issue by MKGitHub** [cocos2d/CocosBuilder#299]
Ability to disable anti-aliasing on nodes.

**Comment by vlidholt** [comment]
I think that anti-alias can only be set per texture in Cocos2d. This is possible to do from code.

**Comment by MKGitHub** [comment]
Stop closing everything without a proper discussion!!!

In this case I don't want my sprites/textures to look different in CocosBuilder from when I run it in the code! So there needs to be an option the set the alias parameter for a texture in CocosBuilder.

**Comment by vlidholt** [comment]
The reason I closed this ticket is not because I dislike the idea, but because there is no good way of implementing this feature. In Cocos2d the anti-aliasing cannot be set for a specific node, but is instead set per texture. Several sprites can share a texture, so setting this property on "a node" would affect other sprites too, and even sprites that share the same sprite sheet. This would also be a problem across ccb-files (what if one ccb-file has it enabled and anther doesn't?).

Another issue with the implementation of this is how the smart sprite sheets work in CocosBuilder. Inside CocosBuilder, they do not share the same texture, but they will when running on a device. Hence, setting the property in CocosBuilder would not give you the same display as when loaded with CCBReader.

**Comment by MKGitHub** [comment]
Thanks for the feedback, that is more like it.

I get your point, but still there should be an options to at least see/preview what the sprite/texture looks like with or without aliasing to minimize the surprising moment when running in the simulator or on a device.

You can easily add a checkbox option "Preview alias / anti-alias" - just a preview, no saving or anything else on all nodes that draw. And also add something like the descibtion above in the manual so you don't have to answer these questions again.

**Comment by ricardoquesada** [comment]
@MKGitHub 
What do you mean by anti-aliasing ? The texture filter option ? These API's ?

``` objective-c
- (void) setAntiAliasTexParameters;
- (void) setAliasTexParameters;
```

As @vlidholt  said, they are associated to a texture, and not a Sprite.  I am thinking that it could be an option of the CocosBuilder's "smart spritesheets" option... although it looks hackish since it would only be available for "Smart spritesheets".

I think the SmartSheet format options should be extended to "non smart spritesheets" as well.
Eg: sprite.png should be sprite.pvr on iOS... and perhaps the "alias" parameter could be added in that dialog.

**Comment by MKGitHub** [comment]
Or at least guide me where to add this in the code as there is alot of code for CocosBuilder, I could use a helping hand to get around in there and start adding features my self.

**Comment by MKGitHub** [comment]
@ricardoquesada
Yes those are the ones, as I see it, it is just an option to turn on/off with a checkbox for a texture in CocosBuilder. And so all sprites using that texture would be effected - but just in CocosBuilder as a preview.

I.e. I'm using a lot of small sprites with small textures and they all have the AliasTexParameters set, but in CocosBuilder they have AntiAliasTexParameters set (by default) and that does not reflect what I actually will be seeing when I run the code. I.e. in CocosBuilder my sprites will be smooth but when I run my game they will be sharp as I wan't them to be. This makes me position sprites incorrectly.

**Comment by ricardoquesada** [comment]
@MKGitHub Adding a "preview in canvas" in CocosBuilder is feasible... but I don't know how easy/difficult/hackish it is.

I think this could be fixed if we could add  "filter" information in the meta data of the PVR files. 
So, when you load a PVR file, it will set the filter automatically.

(PVR v3 files support meta data... but this won't work for .PNG images)

**Comment by MKGitHub** [comment]
The ccbi project file contains what image a node is using,
so we could just add a flag in there?
