### ISSUE TITLE
kCCBMaxTrackedDirectories

### ISSUE THREAD

**Issue by ghost** [cocos2d/CocosBuilder#64]
Why is there a hard limit to the number of tracked directories? It's hardcoded at 50 right now. Is it possible to move that number into preferences so that we don't have to rebuild every time we reach that limit?

**Comment by vlidholt** [comment]
This "feature" is there because CocosBuilder would crash when saving a project in, say, the home directory which as lots and lots of sub directories. Some users doesn't seem to get this crash, so it's possible it's something that has been fixed in Lion.

CocosBuilder 3 will have a new way of handling directories, so this will not be a problem after that update.

**Comment by kirillzuev** [comment]
Any news on updating this constant to some bigger value? Right now I have to rebuild the tool from source with every Mac App Store update, and send the copies to the team members, which is very inconvenient.
